{
 "title": "SQL Efficiency Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "SQL Efficiency Dashboard",
   "type": "timeseries",
   "description": "Show the number of rows accessed for various SQL operations.  This is meant to show the efficiency of the system.",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(stmt_stats{job=\"sql_efficiency_check\"}[20s]) ",
     "legendFormat": "{{lio}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(sql_select_count[20s]))",
     "legendFormat": "select"
    },
    {
     "expr": "sum(rate(sql_insert_count[20s]))",
     "legendFormat": "insert"
    },
    {
     "expr": "sum(rate(sql_delete_count[20s]))",
     "legendFormat": "delete"
    },
    {
     "expr": "sum(rate(sql_update_count[20s]))",
     "legendFormat": "update"
    }
   ]
  },
  {
   "title": "CPU% by Node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sys_cpu_combined_percent_normalized",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Overall Cluster CPU%",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sys_cpu_combined_percent_normalized)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "P99 Latency(ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sql_exec_latency:rate1m:quantile_99/1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}